/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication1;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author jespe
 */
public class AlienFrame extends javax.swing.JFrame {

    /**
     * Creates new form AlienFrame
     */
    private InfDB idb;
    private String inloggadAlienNamn;

    public AlienFrame(InfDB idb, String inloggadAlienNamn) {
        initComponents();
        this.idb = idb;
        this.inloggadAlienNamn = inloggadAlienNamn;
        fyllListorOSV();
        inloggadAlienNamnLBL.setText("Välkommen " + inloggadAlienNamn);
    }

    private void fyllListorOSV() {
        try {

            String query = "SELECT agent.Namn FROM agent "
                    + "INNER JOIN omradeschef ON agent.Agent_ID = omradeschef.Agent_ID "
                    + "INNER JOIN omrade ON omradeschef.Omrade = omrade.Omrades_ID "
                    + "INNER JOIN plats ON omrade.Omrades_ID = plats.Finns_I "
                    + "INNER JOIN alien ON plats.Plats_ID = alien.Plats "
                    + "WHERE alien.Namn = '" + inloggadAlienNamn + "'";
            
            System.out.println(query);
            omradesChefTF.setText(idb.fetchSingle(query));

        } catch (InfException e) {
            Logger.getLogger(AlienFrame.class.getName()).log(Level.SEVERE, null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        omradesChefTF = new javax.swing.JTextField();
        gammaltLosenordTF = new javax.swing.JTextField();
        nyttLosenordTF = new javax.swing.JTextField();
        nyttLosenordTestTF = new javax.swing.JTextField();
        bytLosenordBTN = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        inloggadAlienNamnLBL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        omradesChefTF.setEditable(false);
        omradesChefTF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        bytLosenordBTN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bytLosenordBTN.setText("Byt lösenord");
        bytLosenordBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bytLosenordBTNActionPerformed(evt);
            }
        });

        jLabel13.setText("Nytt lösenord");

        jLabel12.setText("Gammalt lösenord");

        jLabel14.setText("Skriv igen");

        inloggadAlienNamnLBL.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(inloggadAlienNamnLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 393, Short.MAX_VALUE)
                .addComponent(omradesChefTF, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(235, 235, 235)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(61, 61, 61)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bytLosenordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nyttLosenordTestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nyttLosenordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gammaltLosenordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(235, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(omradesChefTF, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(inloggadAlienNamnLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(497, 497, 497))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(188, 188, 188)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(gammaltLosenordTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nyttLosenordTF, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nyttLosenordTestTF, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(bytLosenordBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(189, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bytLosenordBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bytLosenordBTNActionPerformed
        // TODO add your handling code here:

        // Testar om alla fält är i fylda. Om de inte skulla vara det så avbryts lösenords bytningen
        if (gammaltLosenordTF.getText().equals("") || nyttLosenordTF.getText().equals("") || nyttLosenordTestTF.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Du måste fylla i alla fällt!");
            return;
        }

        try {

            String nyttLosenord = nyttLosenordTF.getText();

            // Testar om det nya lösenordet mtachar kontrollen annars avbryts lösenords bytningen
            if (!nyttLosenordTF.getText().equals(nyttLosenordTestTF.getText())) {
                JOptionPane.showMessageDialog(null, "Lösenorden mtachar inte försök igen!");
                return;
            }

            // Testar om det gammla lösenordet matchar det som finns i databasen om det inte skulle det så avbryts lösenords bytningen
            if (!idb.fetchSingle("SELECT Losenord FROM alien WHERE Namn = '" + inloggadAlienNamn + "'").equals(gammaltLosenordTF.getText())) {
                JOptionPane.showMessageDialog(null, "Du skrev in fel lösenord försök igen!");
                return;
            }

            if (JOptionPane.showConfirmDialog(null, "Är du säkerpå att du vill byta lösenord?", "Ja",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Bytning avbröts!");
            }
            String query = "UPDATE alien SET Losenord = '" + nyttLosenord + "' WHERE Namn = '" + inloggadAlienNamn + "'";
            idb.update(query); // Uppdaterar databasen
            JOptionPane.showMessageDialog(null, "Lösenord har nu bytits!");

        } catch (InfException ex) {
            Logger.getLogger(AgentFrame.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Något gick fel försök igen.");
        }
    }//GEN-LAST:event_bytLosenordBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlienFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {

                    new AlienFrame(new InfDB("mibdb", "3306", "mibdba", "mibkey"), "Bobbo").setVisible(true);
                } catch (InfException e) {
                    Logger.getLogger(AlienFrame.class.getName()).log(Level.SEVERE, null, e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bytLosenordBTN;
    private javax.swing.JTextField gammaltLosenordTF;
    private javax.swing.JLabel inloggadAlienNamnLBL;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JTextField nyttLosenordTF;
    private javax.swing.JTextField nyttLosenordTestTF;
    private javax.swing.JTextField omradesChefTF;
    // End of variables declaration//GEN-END:variables
}
